a = input('Digite algo: ')
print('O tipo primitivo do que você digitou é:',type(a))
print('É um numero? ',a.isnumeric())
print('É alfabetico?',a.isalpha())
print('Só tem espaços? ', a.isspace())
print('É alfanumérico?', a.isalnum())
print('Está em minusculo? ', a.islower())
print('Está em maiusculas ',a.isupper())
print('Está capitalizada (tem letras maisculas e minusculas)?', a.istitle())
