nome = str(input('Digite seu nome completo:')).strip()
print('Seu nome em letras maiusculas é.. {}'.format(nome.upper()))
print('Seu nome em letras minusculas é.. {}'.format(nome.lower()))
print('Seu nome tem ao todo.. {}'.format(len(nome) - nome.count(' ')))
separado = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras.'.format(separado[0], len(separado[0])))